# Generated by Django 4.1.3 on 2023-03-17 13:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0006_remove_page_cover'),
    ]

    operations = [
        migrations.DeleteModel(
            name='page',
        ),
    ]
