# Generated by Django 4.1.3 on 2023-02-28 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0002_comics_desc'),
    ]

    operations = [
        migrations.CreateModel(
            name='page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagine', models.ImageField(max_length=200, upload_to='templa/stats/images/')),
                ('comms', models.CharField(max_length=500)),
                ('cover', models.ImageField(max_length=200, upload_to='templa/stats/images/')),
                ('desc', models.CharField(max_length=500)),
            ],
        ),
        migrations.DeleteModel(
            name='comics',
        ),
    ]
