# Generated by Django 4.1.3 on 2023-03-08 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0004_page_name'),
    ]

    operations = [
        migrations.DeleteModel(
            name='newsletter',
        ),
    ]
