# Generated by Django 4.1.3 on 2023-03-11 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('apps', '0005_delete_newsletter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='cover',
        ),
    ]
