# Generated by Django 4.1.3 on 2023-05-06 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('apps', '0007_delete_page'),
    ]

    operations = [
        migrations.CreateModel(
            name='commentfor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comments', models.CharField(default='', max_length=500)),
            ],
        ),
    ]
